### ISSUE TITLE
Remove roave/security-advisories from composer.json

### ISSUE THREAD

**Issue by ralfkuehnel** [OrangeRT/AnonymizeBundle#3]
I would suggest to remove roave/security-advisories from composer.json as this package should not be included in libraries.

Requiring dev-master prevents me to install AnonymizeBundle without changing the minimum stability...

**Comment by ralfkuehnel** [comment]
I made a PR for this #4

**Comment by SanderVerkuil** [comment]
Closed this issue because the PR has been merged.
